insert into dependencia(codigo,nombre) values ('1','(P1) Carro');
insert into dependencia(codigo,nombre) values ('2','(P1)AMPA');
insert into dependencia(codigo,nombre) values ('3','(P1)Aula ADF ');
insert into dependencia(codigo,nombre) values ('4','(P1)Aula Apoyo Orientación');
insert into dependencia(codigo,nombre) values ('5','(P1)Aula Audición y Lenguaje');
insert into dependencia(codigo,nombre) values ('6','(P1)Aula Automatismos');
insert into dependencia(codigo,nombre) values ('7','(P1)Aula Carrocería');
insert into dependencia(codigo,nombre) values ('8','(P1)Aula CGA1 (Mecanografía)');
insert into dependencia(codigo,nombre) values ('9','(P1)Aula CGA2 ( Aula Empresa)');
insert into dependencia(codigo,nombre) values ('10','(P1)Aula Distancia EMV');
insert into dependencia(codigo,nombre) values ('11','(P1)Aula EMV1');
insert into dependencia(codigo,nombre) values ('12','(P1)Aula EMV2');
insert into dependencia(codigo,nombre) values ('13','(P1)Aula Metrología y Ensayos');
insert into dependencia(codigo,nombre) values ('14','(P1)Aula Plástica 1');
insert into dependencia(codigo,nombre) values ('15','(P1)Aula Plástica 2');
insert into dependencia(codigo,nombre) values ('16','(P1)Aula Radio');
insert into dependencia(codigo,nombre) values ('17','(P1)Aula20');
insert into dependencia(codigo,nombre) values ('18','(P1)Aula21');
insert into dependencia(codigo,nombre) values ('19','(P1)Aula22');
insert into dependencia(codigo,nombre) values ('20','(P1)Aula23');
insert into dependencia(codigo,nombre) values ('21','(P1)Aula24');
insert into dependencia(codigo,nombre) values ('22','(P1)Aula25');
insert into dependencia(codigo,nombre) values ('23','(P1)Conserjes  Planta 1');
insert into dependencia(codigo,nombre) values ('24','(P1)Dep Orientación');
insert into dependencia(codigo,nombre) values ('25','(P1)Dep. Administración y Finanzas');
insert into dependencia(codigo,nombre) values ('26','(P1)Dep. FOL');
insert into dependencia(codigo,nombre) values ('27','(P1)Dep. Humanidades');
insert into dependencia(codigo,nombre) values ('28','(P1)Dep. Informática');
insert into dependencia(codigo,nombre) values ('29','(P1)Dep. Mecanizado');
insert into dependencia(codigo,nombre) values ('30','(P1)Dep. Plástica');
insert into dependencia(codigo,nombre) values ('31','(P1)Dep.EMV');
insert into dependencia(codigo,nombre) values ('32','(P1)IF01');
insert into dependencia(codigo,nombre) values ('33','(P1)IF02');
insert into dependencia(codigo,nombre) values ('34','(P1)IF03');
insert into dependencia(codigo,nombre) values ('35','(P1)IF04');
insert into dependencia(codigo,nombre) values ('36','(P1)Sala Visitas');
insert into dependencia(codigo,nombre) values ('37','(P1)Salón de Actos');
insert into dependencia(codigo,nombre) values ('38','(P2) Carro');
insert into dependencia(codigo,nombre) values ('39','(P2)Almacén TIC');
insert into dependencia(codigo,nombre) values ('40','(P2)Aula 30 (Lab Idiomas)');
insert into dependencia(codigo,nombre) values ('41','(P2)Aula 31');
insert into dependencia(codigo,nombre) values ('42','(P2)Aula 32');
insert into dependencia(codigo,nombre) values ('43','(P2)Aula 33');
insert into dependencia(codigo,nombre) values ('44','(P2)Aula 34');
insert into dependencia(codigo,nombre) values ('45','(P2)Aula 35');
insert into dependencia(codigo,nombre) values ('46','(P2)Aula 36');
insert into dependencia(codigo,nombre) values ('47','(P2)Aula 37');
insert into dependencia(codigo,nombre) values ('48','(P2)Aula 38');
insert into dependencia(codigo,nombre) values ('49','(P2)Aula EOC1');
insert into dependencia(codigo,nombre) values ('50','(P2)Aula EOC2-');
insert into dependencia(codigo,nombre) values ('51','(P2)Aula Musica1');
insert into dependencia(codigo,nombre) values ('52','(P2)Aula Musica2');
insert into dependencia(codigo,nombre) values ('53','(P2)Conserjes Planta2 TIC');
insert into dependencia(codigo,nombre) values ('54','(P2)Dep. Economía y Latín');
insert into dependencia(codigo,nombre) values ('55','(P2)Dep. EOC');
insert into dependencia(codigo,nombre) values ('56','(P2)Dep. Idiomas');
insert into dependencia(codigo,nombre) values ('57','(P2)Dep. Matemáticas');
insert into dependencia(codigo,nombre) values ('58','(P2)Dep. Música');
insert into dependencia(codigo,nombre) values ('59','(P2)Dep. Tecnología');
insert into dependencia(codigo,nombre) values ('60','(P2)Informática Bachiderato- Distancia Informática');
insert into dependencia(codigo,nombre) values ('61','(P2)Lab. Tecnología');
insert into dependencia(codigo,nombre) values ('62','(PB) Carro');
insert into dependencia(codigo,nombre) values ('63','(PB)Aula Mecanizado CNC');
insert into dependencia(codigo,nombre) values ('64','(PB)Aula1');
insert into dependencia(codigo,nombre) values ('65','(PB)Aula10');
insert into dependencia(codigo,nombre) values ('66','(PB)Aula12');
insert into dependencia(codigo,nombre) values ('67','(PB)Aula13');
insert into dependencia(codigo,nombre) values ('68','(PB)Aula14');
insert into dependencia(codigo,nombre) values ('69','(PB)Aula15');
insert into dependencia(codigo,nombre) values ('70','(PB)Aula18 Mecanizado');
insert into dependencia(codigo,nombre) values ('71','(PB)Aula2');
insert into dependencia(codigo,nombre) values ('72','(PB)Aula3');
insert into dependencia(codigo,nombre) values ('73','(PB)Aula4');
insert into dependencia(codigo,nombre) values ('74','(PB)Aula5');
insert into dependencia(codigo,nombre) values ('75','(PB)Aula6 Convivencia');
insert into dependencia(codigo,nombre) values ('76','(PB)Aula7');
insert into dependencia(codigo,nombre) values ('77','(PB)Aula8');
insert into dependencia(codigo,nombre) values ('78','(PB)Aula9 Informática');
insert into dependencia(codigo,nombre) values ('79','(PB)Biblioteca');
insert into dependencia(codigo,nombre) values ('80','(PB)Biblioteca PC alumnos');
insert into dependencia(codigo,nombre) values ('81','(PB)Conserjes Planta Baja');
insert into dependencia(codigo,nombre) values ('82','(PB)Dep. Educación Física');
insert into dependencia(codigo,nombre) values ('83','(PB)Dep. Física, Química, Biología y Geología');
insert into dependencia(codigo,nombre) values ('84','(PB)Dep. Lengua Castellana');
insert into dependencia(codigo,nombre) values ('85','(PB)Dep. Mecanizado Oficina');
insert into dependencia(codigo,nombre) values ('86','(PB)Director');
insert into dependencia(codigo,nombre) values ('87','(PB)Fotocopiadora');
insert into dependencia(codigo,nombre) values ('88','(PB)Informática ESO');
insert into dependencia(codigo,nombre) values ('89','(PB)Informática General o Polivalente');
insert into dependencia(codigo,nombre) values ('90','(PB)Jefatura de Estudios');
insert into dependencia(codigo,nombre) values ('91','(PB)Lab. Biología y Geología');
insert into dependencia(codigo,nombre) values ('92','(PB)Lab. Física y Química');
insert into dependencia(codigo,nombre) values ('93','(PB)Sala Profesores');
insert into dependencia(codigo,nombre) values ('94','(PB)Sala Reuniones Jefatura');
insert into dependencia(codigo,nombre) values ('95','(PB)Secretaria');
insert into dependencia(codigo,nombre) values ('96','(PB)Secretario y Administrador');
insert into dependencia(codigo,nombre) values ('97','(PB)Taller Carrocería');
insert into dependencia(codigo,nombre) values ('98','(PB)Taller Colometria');
insert into dependencia(codigo,nombre) values ('99','(PB)Taller EMV');
insert into dependencia(codigo,nombre) values ('100','(PB)Taller Mecanizado');
insert into dependencia(codigo,nombre) values ('101','(PB)Tecnología ESO');

