/*
Created: 27/10/2017
Modified: 27/11/2017
Model: MySQL 5.7
Database: MySQL 5.7
*/


-- Create tables section -------------------------------------------------

-- Table INCIDENCIA

CREATE TABLE `INCIDENCIA`
(
  `INCIDENCIA_ID` Int(11) NOT NULL AUTO_INCREMENT,
  `POSICION_EQUIPO_DEPENDENCIA` Varchar(500),
  `DESCRIPCION` Varchar(500) NOT NULL,
  `COMENTARIO_ADMINISTRADOR` Varchar(500),
  `FECHA_REGISTRO` Date NOT NULL,
  `FECHA_ESTADO_ACTUAL` Datetime NOT NULL,
  `USUARIO_ID` Int NOT NULL,
  `EQUIPO_ID` Int NOT NULL,
  `DEPENDENCIA_ID` Int NOT NULL,
  `ESTADO_ID` Int NOT NULL,
  PRIMARY KEY (`INCIDENCIA_ID`)
)
;

CREATE INDEX `IX_Relationship3` ON `INCIDENCIA` (`USUARIO_ID`)
;

CREATE INDEX `IX_Relationship7` ON `INCIDENCIA` (`EQUIPO_ID`)
;

CREATE INDEX `IX_Relationship12` ON `INCIDENCIA` (`DEPENDENCIA_ID`)
;

CREATE INDEX `IX_Relationship15` ON `INCIDENCIA` (`ESTADO_ID`)
;

-- Create triggers for table INCIDENCIA

delimiter //
CREATE  TRIGGER `GENERAR_HISTORIAL`
  AFTER
  UPDATE
  ON `INCIDENCIA`
  FOR EACH ROW
  BEGIN
    if OLD.ESTADO_ID != NEW.ESTADO_ID THEN
        insert into HISTORIAL(FECHA,INCIDENCIA_ID,ESTADO_ID)

            values(OLD.FECHA_ESTADO_ACTUAL,OLD.INCIDENCIA_ID,OLD.ESTADO_ID);

    END IF;    
END
//
delimiter 

-- Table USUARIO

CREATE TABLE `USUARIO`
(
  `USUARIO_ID` Int NOT NULL AUTO_INCREMENT,
  `CUENTA` Varchar(100) NOT NULL,
  `NOMBRE` Varchar(100),
  `APELLIDO` Varchar(100),
  `DEPARTAMENTO` Varchar(100),
  PRIMARY KEY (`USUARIO_ID`)
)
;

ALTER TABLE `USUARIO` ADD UNIQUE `CUENTA` (`CUENTA`)
;

-- Table DEPENDENCIA

CREATE TABLE `DEPENDENCIA`
(
  `DEPENDENCIA_ID` Int NOT NULL AUTO_INCREMENT,
  `CODIGO` Varchar(10) NOT NULL,
  `NOMBRE` Varchar(100) NOT NULL,
  PRIMARY KEY (`DEPENDENCIA_ID`)
)
;

ALTER TABLE `DEPENDENCIA` ADD UNIQUE `CODIGO` (`CODIGO`)
;

ALTER TABLE `DEPENDENCIA` ADD UNIQUE `NOMBRE` (`NOMBRE`)
;

-- Table TIPO_EQUIPO

CREATE TABLE `TIPO_EQUIPO`
(
  `TIPO_EQUIPO_ID` Int NOT NULL AUTO_INCREMENT,
  `CODIGO` Varchar(10) NOT NULL,
  `NOMBRE` Varchar(100) NOT NULL,
  PRIMARY KEY (`TIPO_EQUIPO_ID`)
)
;

ALTER TABLE `TIPO_EQUIPO` ADD UNIQUE `CODIGO` (`CODIGO`)
;

ALTER TABLE `TIPO_EQUIPO` ADD UNIQUE `NOMBRE` (`NOMBRE`)
;

-- Table EQUIPO

CREATE TABLE `EQUIPO`
(
  `EQUIPO_ID` Int NOT NULL AUTO_INCREMENT,
  `NUMERO_ETIQUETA_CONSEJERIA` Varchar(100) NOT NULL,
  `TIPO_EQUIPO_ID` Int NOT NULL,
  PRIMARY KEY (`EQUIPO_ID`)
)
;

CREATE INDEX `IX_Relationship5` ON `EQUIPO` (`TIPO_EQUIPO_ID`)
;

ALTER TABLE `EQUIPO` ADD UNIQUE `NUMERO_ETIQUETA_CONSEJERIA` (`NUMERO_ETIQUETA_CONSEJERIA`)
;

-- Table ESTADO

CREATE TABLE `ESTADO`
(
  `ESTADO_ID` Int NOT NULL AUTO_INCREMENT,
  `CODIGO` Varchar(10) NOT NULL,
  `NOMBRE` Varchar(100) NOT NULL,
  PRIMARY KEY (`ESTADO_ID`)
)
;

ALTER TABLE `ESTADO` ADD UNIQUE `CODIGO` (`CODIGO`)
;

ALTER TABLE `ESTADO` ADD UNIQUE `NOMBRE` (`NOMBRE`)
;

-- Table HISTORIAL

CREATE TABLE `HISTORIAL`
(
  `HISTORIAL_ID` Int NOT NULL AUTO_INCREMENT,
  `FECHA` Datetime NOT NULL,
  `INCIDENCIA_ID` Int(11) NOT NULL,
  `ESTADO_ID` Int NOT NULL,
  PRIMARY KEY (`HISTORIAL_ID`)
)
;

CREATE INDEX `IX_Relationship9` ON `HISTORIAL` (`INCIDENCIA_ID`)
;

CREATE INDEX `IX_Relationship10` ON `HISTORIAL` (`ESTADO_ID`)
;

-- Table CONFIGURACION

CREATE TABLE `CONFIGURACION`
(
  `EMPRESA_CONSEJERIA_NOMBRE` Varchar(100) NOT NULL DEFAULT 100,
  `EMPRESA_CONSEJERIA_TELEFONO` Varchar(100) NOT NULL,
  `EMPRESA_CONSEJERIA_EMAIL` Varchar(100) NOT NULL,
  `IES_NOMBRE` Varchar(100) NOT NULL,
  `IES_CIF` Varchar(100) NOT NULL,
  `IES_CODIGO_CENTRO` Varchar(100) NOT NULL,
  `IES_PERSONA_CONTACTO_NOMBRE` Varchar(100) NOT NULL,
  `IES_PERSONA_CONTACTO_APELLIDO1` Varchar(100) NOT NULL,
  `IES_PERSONA_CONTACTO_APELLIDO2` Varchar(100) NOT NULL,
  `IES_EMAIL` Varchar(100) NOT NULL,
  `ESTADO_INICIAL_INCIDENCIA` Int NOT NULL,
  `ESTADO_FINAL_INCIDENCIA` Int NOT NULL,
  `LDAP_URL` Varchar(200) NOT NULL,
  `LDAP_DOMINIO` Varchar(100) NOT NULL,
  `LDAP_DN` Varchar(100) NOT NULL,
  `LDAP_ATRIBUTO_CUENTA` Varchar(100) NOT NULL,
  `LDAP_ATRIBUTO_NOMBRE` Varchar(100) NOT NULL,
  `LDAP_ATRIBUTO_APELLIDO` Varchar(100) NOT NULL,
  `LDAP_ATRIBUTO_DEPARTAMENTO` Varchar(100) NOT NULL,
  `LDAP_ATRIBUTO_PERFIL` Varchar(100) NOT NULL
)
;

CREATE INDEX `IX_Relationship13` ON `CONFIGURACION` (`ESTADO_INICIAL_INCIDENCIA`)
;

CREATE INDEX `IX_Relationship14` ON `CONFIGURACION` (`ESTADO_FINAL_INCIDENCIA`)
;

-- Create foreign keys (relationships) section ------------------------------------------------- 


ALTER TABLE `INCIDENCIA` ADD CONSTRAINT `Relationship3` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`USUARIO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `EQUIPO` ADD CONSTRAINT `Relationship5` FOREIGN KEY (`TIPO_EQUIPO_ID`) REFERENCES `TIPO_EQUIPO` (`TIPO_EQUIPO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `INCIDENCIA` ADD CONSTRAINT `Relationship7` FOREIGN KEY (`EQUIPO_ID`) REFERENCES `EQUIPO` (`EQUIPO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `HISTORIAL` ADD CONSTRAINT `Relationship9` FOREIGN KEY (`INCIDENCIA_ID`) REFERENCES `INCIDENCIA` (`INCIDENCIA_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `HISTORIAL` ADD CONSTRAINT `Relationship10` FOREIGN KEY (`ESTADO_ID`) REFERENCES `ESTADO` (`ESTADO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `INCIDENCIA` ADD CONSTRAINT `Relationship12` FOREIGN KEY (`DEPENDENCIA_ID`) REFERENCES `DEPENDENCIA` (`DEPENDENCIA_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `CONFIGURACION` ADD CONSTRAINT `Relationship13` FOREIGN KEY (`ESTADO_INICIAL_INCIDENCIA`) REFERENCES `ESTADO` (`ESTADO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `CONFIGURACION` ADD CONSTRAINT `Relationship14` FOREIGN KEY (`ESTADO_FINAL_INCIDENCIA`) REFERENCES `ESTADO` (`ESTADO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `INCIDENCIA` ADD CONSTRAINT `Relationship15` FOREIGN KEY (`ESTADO_ID`) REFERENCES `ESTADO` (`ESTADO_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


