/*
Created: 27/10/2017
Modified: 27/11/2017
Model: MySQL 5.7
Database: MySQL 5.7
*/


-- Drop relationships section -------------------------------------------------

ALTER TABLE `INCIDENCIA` DROP FOREIGN KEY `Relationship15`
;
ALTER TABLE `CONFIGURACION` DROP FOREIGN KEY `Relationship14`
;
ALTER TABLE `CONFIGURACION` DROP FOREIGN KEY `Relationship13`
;
ALTER TABLE `INCIDENCIA` DROP FOREIGN KEY `Relationship12`
;
ALTER TABLE `HISTORIAL` DROP FOREIGN KEY `Relationship10`
;
ALTER TABLE `HISTORIAL` DROP FOREIGN KEY `Relationship9`
;
ALTER TABLE `INCIDENCIA` DROP FOREIGN KEY `Relationship7`
;
ALTER TABLE `EQUIPO` DROP FOREIGN KEY `Relationship5`
;
ALTER TABLE `INCIDENCIA` DROP FOREIGN KEY `Relationship3`
;


-- Drop keys for tables section -------------------------------------------------

-- ALTER TABLE `HISTORIAL` DROP PRIMARY KEY
-- ALTER TABLE `ESTADO` DROP PRIMARY KEY
ALTER TABLE `ESTADO` DROP KEY `CODIGO`
;
ALTER TABLE `ESTADO` DROP KEY `NOMBRE`
;
-- ALTER TABLE `EQUIPO` DROP PRIMARY KEY
ALTER TABLE `EQUIPO` DROP KEY `NUMERO_ETIQUETA_CONSEJERIA`
;
-- ALTER TABLE `TIPO_EQUIPO` DROP PRIMARY KEY
ALTER TABLE `TIPO_EQUIPO` DROP KEY `CODIGO`
;
ALTER TABLE `TIPO_EQUIPO` DROP KEY `NOMBRE`
;
-- ALTER TABLE `DEPENDENCIA` DROP PRIMARY KEY
ALTER TABLE `DEPENDENCIA` DROP KEY `CODIGO`
;
ALTER TABLE `DEPENDENCIA` DROP KEY `NOMBRE`
;
-- ALTER TABLE `USUARIO` DROP PRIMARY KEY
ALTER TABLE `USUARIO` DROP KEY `CUENTA`
;
-- ALTER TABLE `INCIDENCIA` DROP PRIMARY KEY


-- Drop indexes section -------------------------------------------------

DROP INDEX `IX_Relationship13` ON `CONFIGURACION`
;

DROP INDEX `IX_Relationship14` ON `CONFIGURACION`
;

DROP INDEX `IX_Relationship9` ON `HISTORIAL`
;

DROP INDEX `IX_Relationship10` ON `HISTORIAL`
;

DROP INDEX `IX_Relationship5` ON `EQUIPO`
;

DROP INDEX `IX_Relationship3` ON `INCIDENCIA`
;

DROP INDEX `IX_Relationship7` ON `INCIDENCIA`
;

DROP INDEX `IX_Relationship12` ON `INCIDENCIA`
;

DROP INDEX `IX_Relationship15` ON `INCIDENCIA`
;


-- Drop tables section ---------------------------------------------------

DROP TABLE `CONFIGURACION`
;
DROP TABLE `HISTORIAL`
;
DROP TABLE `INCIDENCIA`
;
DROP TABLE `ESTADO`
;
DROP TABLE `TIPO_EQUIPO`
;
DROP TABLE `EQUIPO`
;
DROP TABLE `DEPENDENCIA`
;
DROP TABLE `USUARIO`
;




